
name: AutoBuy  Continuous Integration
run-name: ${{ github.actor }} is learning CI/CD & GitHub Actions for a project

on: # workflow_dispatch
  push:
    branches:
      - main

jobs:
  Selenium-Test:
    runs-on: ubuntu-latest

    steps:
      
      - name: Download Chrome WebDriver # chrome v: 117.0.5938.149
        run: |
          driver_version="117.0.5938.92"
          CHROME_DRIVER_URL="https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/${driver_version}/linux64/chromedriver-linux64.zip"
          wget -N ${CHROME_DRIVER_URL}
          unzip chromedriver-linux64.zip
          cd chromedriver-linux64
          chmod +x chromedriver
          mv chromedriver /usr/local/bin/
      
      - name: Setting up Chrome
        run: |
          chrome --version

      # - name: Set up Python
      #   uses: actions/setup-python@v2
      #   with:
      #     python-version: 3.11.3

      # - name: Checkout code
      #   uses: actions/checkout@v2

      # - name: Install dependencies
      #   run: |
      #     python -m pip install --upgrade pip
      #     pip install -r requirements.txt
          
      # - name: Run tests
      #   run: |
      #     pytest src/tests
          
      # - name: Lint code
      #   run: |
      #     pylint src